### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by xremix** [sixrevisions/css-ghost-buttons#1]
Hi @sixrevisions ,

I made a fork of your library as I liked the style. What I didn't like was all the css reset and other site styles so I separated this into 2 files. Also I switched from css to SCSS. 

If you want to take a look, please check it out here:
https://github.com/xremix/css-ghost-buttons

**Comment by sixrevisions** [comment]
@xremix Yes, what you did is great. It's a good idea to separate the essential style rules for the ghost buttons versus the style rules for the demo page (CSS reset, etc.). This makes easily distributable and reusable. Your fork is also more maintainable with Sass + a task runner to build the distribution code. Thanks and keep up the great work.

**Comment by xremix** [comment]
Great, I'm glad you like the work!
